-- Cake Drama -- seed data
truncate table public.products, public.specials, public.partners restart identity cascade;

insert into public.products (category, name, image, weight, packaging, storage, shelf_life, thawing, sort_order) values
('castella', 'Monster Castella Tiramisu', '/images/products/monster_castella_tiramisu.jpg', '130 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 0),
('castella', 'Monster Castella Chocolate', '/images/products/monster_castella_chocolate.jpg', '130 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 1),
('castella', 'Monster Castella Cream Cheese', '/images/products/monster_castella_creamcheese.jpg', '130 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 2),
('castella', 'Milk Cream Castella', '/images/products/milk_cream_castella.jpg', '130 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 3),
('castella', 'Cookie & Cream Castella', '/images/products/cookie_cream_castella.jpg', '130 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 4),
('big_cake', 'New York Cheese Cake 5P', '/images/products/newyork_cheesecake.jpg', '650 грамм / баг', 'Нэг хайрцагт 4 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 5),
('big_cake', 'Chocolate Mud Cake 5P', '/images/products/chocolate_mud_cake.jpg', '500 грамм / баг', 'Нэг хайрцаганд 16 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 6),
('big_cake', 'Chocolate Rocher Cake 5P', '/images/products/chocolate_rocher_cake.jpg', '400 грамм / баг', 'Нэг хайрцаганд 24 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 7),
('big_cake', 'Souffle Cheese Cake 5P', '/images/products/souffle_cheesecake.jpg', '425 грамм / баг', 'Нэг хайрцаганд 24 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 8),
('big_cake', 'Oreo Cream Cheese Cake 5P', '/images/products/oreo_creamcheese_cake.jpg', '625 грамм / баг (570 х 480 х 250 мм)', 'Нэг хайрцаганд 16 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 9),
('big_cake', 'Dolce Tiramisu Cake 5P', '/images/products/dolce_tiramisu_cake.jpg', '650 грамм / баг (570 х 480 х 250 мм)', 'Нэг хайрцаганд 16 баг', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 10),
('roll_snack', 'Fresh Cream Roll Cake', '/images/products/fresh_cream_roll_cake.jpg', '260 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 11),
('roll_snack', 'Chocolate Roll Cake', '/images/products/chocolate_roll_cake.jpg', '260 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 12),
('roll_snack', 'Bagel Chip Honey Butter', '/images/products/bagel_chip_honey_butter.jpg', '50 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Өрөөний температурт хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', NULL, 13),
('roll_snack', 'Bagel Chip Garlic Butter', '/images/products/bagel_chip_garlic_butter.jpg', '50 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Өрөөний температурт хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', NULL, 14),
('roll_snack', 'Zero Tiramisu', '/images/products/zero_tiramisu.jpg', '100 грамм', 'Нэг бүрийн савлагаа (1 ширхэг / хайрцаг)', 'Хөлдөөсөн хэлбэрээр хадгална', 'Үйлдвэрлэсэн өдрөөс хойш 12 сар', 'Хөргөгчинд 2 цаг байлгаж гэсгээнэ', 15),
('donut', 'Glazed', '/images/products/donut_glazed.jpg', NULL, NULL, NULL, NULL, NULL, 16),
('donut', 'Choco-Frost', '/images/products/donut_choco_frost.jpg', NULL, NULL, NULL, NULL, NULL, 17),
('donut', 'Choco-Ring', '/images/products/donut_choco_ring.jpg', NULL, NULL, NULL, NULL, NULL, 18),
('donut', 'Berliner', '/images/products/donut_berliner.jpg', NULL, NULL, NULL, NULL, NULL, 19),
('mini_donut', 'Maple-Ring', '/images/products/minidonut_maple_ring.jpg', NULL, NULL, NULL, NULL, NULL, 20),
('mini_donut', 'Choco-Ring', '/images/products/minidonut_choco_ring.jpg', NULL, NULL, NULL, NULL, NULL, 21),
('mini_donut', 'Strawberry Flavored-Ring', '/images/products/minidonut_strawberry.jpg', NULL, NULL, NULL, NULL, NULL, 22),
('mini_donut', 'White Rainbow', '/images/products/minidonut_white_rainbow.jpg', NULL, NULL, NULL, NULL, NULL, 23),
('fatcaron', 'Fat-Caron 1', '/images/products/fatcaron_1.jpg', NULL, NULL, NULL, NULL, NULL, 24),
('fatcaron', 'Fat-Caron 2', '/images/products/fatcaron_2.jpg', NULL, NULL, NULL, NULL, NULL, 25),
('fatcaron', 'Fat-Caron 3', '/images/products/fatcaron_3.jpg', NULL, NULL, NULL, NULL, NULL, 26),
('fatcaron', 'Fat-Caron 4', '/images/products/fatcaron_4.jpg', NULL, NULL, NULL, NULL, NULL, 27),
('fatcaron', 'Fat-Caron 5', '/images/products/fatcaron_5.jpg', NULL, NULL, NULL, NULL, NULL, 28),
('fatcaron', 'Fat-Caron 6', '/images/products/fatcaron_6.jpg', NULL, NULL, NULL, NULL, NULL, 29);

insert into public.specials (title, image, tags, description, sort_order) values
('Zero Sugar Tiramisu', '/images/special_zero_sugar_tiramisu.jpg', ARRAY['NO SUGAR','NO GLUTEN','NO COMPROMISE']::text[], 'Элсэн чихэр, гурилын талаар санаа зовохгүй. Тирамисутийн баялаг амт, зөөлөн бүтэц, төгс мэдрэмжийг хэвээр хадгалсан Zero Sugar Tiramisu.', 0),
('Croffle', '/images/special_croffle.jpg', '{}', 'Кроасантны зуурмагийг вафль хэлбэрт шарж бэлтгэсэн, гаднаа шарзгинуур, дотроо зөөлөн Croffle.', 1),
('Condensed Milk Butter Roll', '/images/special_condensed_milk_roll.jpg', '{}', 'Өтгөрүүлсэн сүүтээр зөөлрүүлэн хөвсийлгөсөн, дотроо өтгөн цөцгийтэй зөөлөн мока талх.', 2);

insert into public.partners (name, logo, sort_order) values
('Homeplus', 'homeplus', 0),
('CU (Coop)', 'cu_coop', 1),
('CU', 'cu', 2),
('CJ Freshway', 'cj_freshway1', 3),
('CJ Freshway', 'cj_freshway2', 4),
('KORAIL', 'korail', 5),
('NongHyup', 'nonghyup', 6),
('Hanwha', 'hanwha', 7),
('Ourhome', 'ourhome', 8),
('Emart', 'emart', 9),
('Lotte Mart Maxx', 'lottemart_maxx', 10),
('Starbucks', 'starbucks', 11),
('Ediya Coffee', 'ediya_coffee', 12),
('Hollys Coffee', 'hollys_coffee', 13),
('Paul Bassett', 'paul_bassett', 14),
('Twosome Place', 'twosome_place', 15),
('Coffee Bene', 'coffeebene', 16),
('The Venti', 'theventi', 17),
('Knotted', 'knotted', 18),
('Sulbing', 'sulbing', 19),
('Gong Cha', 'gongcha', 20),
('Mammoth Coffee', 'mammoth_coffee', 21),
('Juicy', 'juicy', 22),
('Yogerpresso', 'yogerpresso', 23),
('Sangdo Foodmoment', 'sangdo_foodmoment', 24),
('SRC', 'src', 25),
('The Slow Made', 'the_slow_made', 26),
('KTSC', 'ktsc', 27),
('Mega Coffee', 'mega_coffee', 28),
('B Coffee', 'b_coffee', 29),
('Dallyeun Coffee', 'dallyeun_coffee', 30),
('Hands Coffee', 'hands_coffee', 31),
('Baekgeumdang', 'baekgeumdang', 32),
('U:Dally', 'u_dally', 33),
('About Coffee', 'about_coffee', 34),
('Caffe Tiamo', 'caffe_tiamo', 35),
('Port Can Coffee', 'port_can_coffee', 36),
('Bavin''s Coffee', 'bavins_coffee', 37),
('Cafe Heeda', 'cafe_heeda', 38),
('Fodist', 'fodist', 39),
('Sushiro', 'sushiro', 40),
('Silla Myeongkwa', 'silla_myeongkwa', 41);

-- images массив баганыг цорын ганц image-ээр дүүргэх (0002 migration-той хамт ажиллана)
update public.products set images = array[image] where images = '{}';
